### ISSUE TITLE
Firebase Issues

### ISSUE THREAD

**Issue by PartapSBimrah** [AlucardLogistics/SocialNetworkApp#1]
I have issues with firebase authenticating. I have noticed that getDownloadUrl deprecated by Firebase. It shows error. fix this and let me know. 
![Screenshot (9)](https://user-images.githubusercontent.com/39325207/54269981-68665200-45a4-11e9-8403-02fb96c71be3.png)

**Comment by AlucardLogistics** [comment]
hey Kanwarpartap Singh, 
- I have updated the app to AndroidX architecture
- I have fixed the deprecated downloadUrl method, was moved to StorageReference class
- Updated some libraries to support AndroidX

Everything should work. Thank you for the message :)
