### ISSUE TITLE
Some Error in this project

### ISSUE THREAD

**Issue by PartapSBimrah** [AlucardLogistics/SocialNetworkApp#2]
Hi,

Please see the screenshot and let me know how to solve this problem. The same error occurred in two-three java files and differ error in Bottom navigations java file
![Screenshot (11)](https://user-images.githubusercontent.com/39325207/54518345-06ce2b00-498a-11e9-8abe-87421e731847.png)
![Screenshot (12)](https://user-images.githubusercontent.com/39325207/54518347-06ce2b00-498a-11e9-9fcc-fc8e37d9239b.png)
![Screenshot (13)](https://user-images.githubusercontent.com/39325207/54518348-0766c180-498a-11e9-84da-8624d531592c.png)
![Screenshot (14)](https://user-images.githubusercontent.com/39325207/54518350-0766c180-498a-11e9-8d13-9ad11993f571.png)

.

**Comment by PartapSBimrah** [comment]
Also having errors in Manifest file. S
![Screenshot (15)](https://user-images.githubusercontent.com/39325207/54519301-367e3280-498c-11e9-9126-d6c916d69f10.png)
ee this

**Comment by AlucardLogistics** [comment]
Just delete the app and download it again.
I had to update libraries too to work with AndroidX.
I ran it in it works on my end.

**Comment by PartapSBimrah** [comment]
Okay. Thanks for response as soon as possibleThanks Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alucard Logistics <notifications@github.com> Date: 27/03/2019  11:15 pm  (GMT+05:30) To: AlucardLogistics/SocialNetworkApp <SocialNetworkApp@noreply.github.com> Cc: Kanwarpartap Singh <Kanwarpartapsinghbimrah@gmail.com>, Author <author@noreply.github.com> Subject: Re: [AlucardLogistics/SocialNetworkApp] Some Error in this project (#2) Just delete the app and download it again.
I had to update libraries too to work with AndroidX.
I ran it in it works on my end.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AlucardLogistics/SocialNetworkApp","title":"AlucardLogistics/SocialNetworkApp","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AlucardLogistics/SocialNetworkApp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlucardLogistics in #2: Just delete the app and download it again.\r\nI had to update libraries too to work with AndroidX.\r\nI ran it in it works on my end."}],"action":{"name":"View Issue","url":"https://github.com/AlucardLogistics/SocialNetworkApp/issues/2#issuecomment-477275824"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AlucardLogistics/SocialNetworkApp/issues/2#issuecomment-477275824",
"url": "https://github.com/AlucardLogistics/SocialNetworkApp/issues/2#issuecomment-477275824",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
